stages:
  - build

build-devel:
  stage: build
  image: moby/buildkit:latest
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
    - buildctl-daemonless.sh build --export-cache type=registry,ref=$CACHE_IMAGE --import-cache type=registry,ref=$CACHE_IMAGE --frontend dockerfile.v0 --local context=${CI_PROJECT_DIR} --local dockerfile=${CI_PROJECT_DIR}/devel/Dockerfile --output type=image,name=${CI_REGISTRY_IMAGE}:devel,push=true
    - buildctl-daemonless.sh build --export-cache type=registry,ref=$CACHE_IMAGE --import-cache type=registry,ref=$CACHE_IMAGE --frontend dockerfile.v0 --local context=${CI_PROJECT_DIR} --local dockerfile=${CI_PROJECT_DIR}/devel/Dockerfile --output type=image,name=${CI_REGISTRY_IMAGE}:devel${CI_COMMIT_SHORT_SHA},push=true
  rules:
    - when: manual
  allow_failure: true

build-tag:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --destination ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: $CI_COMMIT_TAG
