stages:
  - build
  - build-devel
  - build-tag

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      variables:
        BUILD_DEVEL: "True"
        RUN_UNIT_TESTS: "True"
        BUILD_COMMIT_SHORT: "True"
        RUN_FUNCTIONAL_TESTS: "True"
        LATEST_TAG: "dev"
    - if: $CI_COMMIT_TAG
      variables:
        BUILD_DEVEL: "False"
        RUN_UNIT_TESTS: "True"
        BUILD_COMMIT_SHORT: "False"
        RUN_FUNCTIONAL_TESTS: "True"
        LATEST_TAG: "latest"
    - when: never


variables:
  JUPYTERHUB_VERSION: "2.3.1"

build:
  # when: manual
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --cache=true --cache-copy-layers=true --build-arg JUPYTERHUB_VERSION="${JUPYTERHUB_VERSION}" --destination ${CI_REGISTRY_IMAGE}:${LATEST_TAG}
  rules:
    - if: $BUILD_COMMIT_SHORT == "True"

build-devel:
  # when: manual
  stage: build-devel
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --cache=true --cache-copy-layers=true --dockerfile ${CI_PROJECT_DIR}/devel/Dockerfile --build-arg JUPYTERHUB_VERSION="${JUPYTERHUB_VERSION}" --destination ${CI_REGISTRY_IMAGE}:devel
  rules:
    - if: $BUILD_DEVEL == "True"

build-tag:
  stage: build-tag
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} --build-arg JUPYTERHUB_VERSION="${JUPYTERHUB_VERSION}" --destination ${CI_REGISTRY_IMAGE}:latest
  rules:
    - if: $CI_COMMIT_TAG
